Drop TABLE Wijzingen cascade constraints;
DROP TABLE GROEP cascade constraints;
DROP TABLE Boodschappenlijst cascade constraints;
DROP TABLE Product cascade constraints;
DROP table Gebruiker cascade constraints;
DROP TABLE Boodschappenlijst_Producten cascade constraints;
DROP TABLE Groep_Gebruikers cascade constraints;

Create TABLE Gebruiker(
ID			NUMBER(10)			PRIMARY KEY,
Email		VARCHAR2(30)		NOT NULL UNIQUE,
Wachtwoord 	VARCHAR2(30) 	NOT NULL,
Naam		VARCHAR2(30)	NOT NULL,
status 		NUMBER(1)       DEFAULT '1'     CHECK (status BETWEEN 0 AND 1)

);

CREATE TABLE GROEP(
ID			NUMBER(10)		PRIMARY KEY,
Naam		VARCHAR2(30)	NOT NULL UNIQUE,
Eigenaar	VARCHAR2(30)	NOT NULL
);

CREATE TABLE PRODUCT(
ID				NUMBER(10)		PRIMARY KEY,
Naam			VARCHAR2(30)	NOT NULL,
PRIJS			NUMBER(30) 	NOT NULL,
Imgurl			VARCHAR2(50)	NULL,
LaastGewijzigd	DATE		NULL
);

CREATE TABLE BOODSCHAPPENLIJST(
ID				NUMBER(10)		PRIMARY KEY,
GROEP_ID		NUMBER(10)		NOT NULL,
TotaalPrijs		NUMBER(30)	NULL,
STARTDATUM    DATE        NOT NULL,
EINDDATUM     DATE        NULL
);

CREATE TABLE GROEP_GEBRUIKERS(
GROEP_ID      NUMBER(10)		NOT NULL,
GEBRUIKER_ID  NUMBER(10)		NOT NULL,
CONSTRAINT  pk_GroepGebruiker PRIMARY KEY(GROEP_ID, GEBRUIKER_ID)
);

CREATE TABLE BOODSCHAPPENLIJST_PRODUCTEN(
BOODSCHAPPENLIJST_ID	NUMBER(10)	NOT NULL,
PRODUCT_ID		NUMBER(10)		NOT NULL,
GEBRUIKER_ID		NUMBER(10)		NOT NULL,
CONSTRAINT	pk_BOODSCHAPPRODUCT PRIMARY KEY(BOODSCHAPPENLIJST_ID, Gebruiker_ID)
);

CREATE TABLE WIJZINGEN(
ID				NUMBER(10)		PRIMARY KEY,
PRODUCT_ID		NUMBER(10)		NOT NULL,
GEBRUIKER_ID		NUMBER(10)		NOT NULL,
WIJZING			VARCHAR2(500)	NULL,
DATUM			DATE			NULL
);

ALTER TABLE GROEP_GEBRUIKERS				ADD FOREIGN KEY (GROEP_ID) REFERENCES GROEP(ID);
ALTER TABLE GROEP_GEBRUIKERS				ADD FOREIGN KEY (GEBRUIKER_ID) REFERENCES GEBRUIKER(ID);
ALTER TABLE BOODSCHAPPENLIJST_PRODUCTEN ADD FOREIGN KEY (BOODSCHAPPENLIJST_ID) REFERENCES BOODSCHAPPENLIJST(ID);
ALTER TABLE BOODSCHAPPENLIJST_PRODUCTEN ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID);
ALTER TABLE BOODSCHAPPENLIJST_PRODUCTEN ADD FOREIGN KEY (GEBRUIKER_ID) REFERENCES GEBRUIKER(ID);
ALTER TABLE BOODSCHAPPENLIJST 			ADD FOREIGN KEY (GROEP_ID) REFERENCES GROEP(ID);
ALTER TABLE WIJZINGEN					ADD FOREIGN KEY(PRODUCT_ID)	REFERENCES PRODUCT(ID);
ALTER TABLE WIJZINGEN 					ADD FOREIGN KEY (GEBRUIKER_ID) REFERENCES GEBRUIKER(ID);